#!/usr/bin/with-contenv sh

[ -e /config/host_keys ] || mkdir -p /config/host_keys
[ -e /config/authorized_keys ] || mkdir -p /config/authorized_keys
[ -e /var/run/sshd ] || mkdir -p /var/run/sshd

for i in rsa dsa ecdsa ed25519; do
    [ -e /config/host_keys/ssh_host_${i}_key ] || ssh-keygen -f /config/host_keys/ssh_host_${i}_key -N '' -t ${i}
done

# update sshd_config
sed -i 's/#HostKey \/etc\/ssh\/ssh_host_/HostKey \/config\/host_keys\/ssh_host_/g' /etc/ssh/sshd_config
sed -i 's/#AuthorizedKeysFile.*/AuthorizedKeysFile \/config\/authorized_keys\/%u/' /etc/ssh/sshd_config
sed -i 's/#PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config

# permissions
chmod 0755 /var/run/sshd
chown -R root:root /config
